@SKStreaming.ApiApp_HostAddress = http://localhost:5017

POST {{SKStreaming.ApiApp_HostAddress}}/api/chat/complete/
Accept: application/json
Content-Type: application/json

{
  "prompt": "Why is the sky blue?"
}

###

POST {{SKStreaming.ApiApp_HostAddress}}/api/chat/complete/streaming
Accept: application/json
Content-Type: application/json

{
  "prompt": "Why is the sky blue?"
}

###

POST {{SKStreaming.ApiApp_HostAddress}}/api/bookings/streaming
Accept: application/json
Content-Type: application/json

{
  "prompt": "Book a meeting room."
}
